package com.raju.getmyshow.booking.dto.request;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

import java.util.List;

/**
 * Example JSON:
 * {
 *     "userId": 1,
 *     "showId": 2,
 *     "seatIds": [1, 2, 3],
 *     "sessionId": "xyz1234"
 * }
 */
public class CreateBookingRequest {

    @NotNull(message = "User ID is required")
    private Long userId;

    @NotNull(message = "Show ID is required")
    private Long showId;

    @NotEmpty(message = "At least one seat must be selected")
    private List<Long> seatIds;

    /**
     * 💡 Session ID for seat locking
     * - Generated by frontend
     * - Used to track which user locked which seats
     * - Format: "session-{UUID}" or "temp-booking-{UUID}"
     */
    @NotNull(message = "Session ID is required")
    private String sessionId;
}
